### ISSUE TITLE
Pole měření - čištění dat

### ISSUE THREAD

**Issue by GoogleCodeExporter** [incad/czbrd#59]
```
Měření:pole předěláno na Combo ještě je pozatřebí vyčistit data a 
sjednotit na hodnoty podporované v Combo poli.

```

Original issue reported on code.google.com by `martin.n...@incad.cz` on 10 Feb 2015 at 1:29

**Comment by Martin-Novacek-csCZ** [comment]
Odstarnění štítku: Časová náročnost 002

**Comment by Neoralova** [comment]
Posílám od týmu NK doplněnou excel tabulku KDE. Tam, kde jsou uvedena pouze čísla nebo typ stránky nejsme schopni označit místo. Pokud by to šlo, tak bychom v těchto případech chtěli přesunout hodnotu do poznámky a místo KDE nechat prázdné.
[pruzkum_zmena oznaceni JN.xlsx](https://github.com/incad/czbrd/files/108368/pruzkum_zmena.oznaceni.JN.xlsx)

**Comment by Martin-Novacek-csCZ** [comment]
Data byla opravna dle přiloženého Excelu.
