### ISSUE TITLE
Kontorla formuláře na Testovasím serveru

### ISSUE THREAD

**Issue by Martin-Novacek-csCZ** [incad/czbrd#79]
Potřeboval bych od Vás kontorlu formuláře nasazeného na Testovací server.
Je tam nasazena nová verze s jedním formulářem, který by měl obsahovat všechna pole, která ve formulářích chcete mít.

Až bude odsouhlaseno že formuláře je kompletní, tak začneme řešit rozdělení na více formulářů dle Zásahu.

**Comment by Neoralova** [comment]
Rozsah polí formuláře je v pořádku. Jenom zde zůstaly drobné chyby: V části Počet zásahů je potřeba nahradit slovo živelné za živelní. V části typologie v kolonce ochranný obal je chybně vložena hodnota - Plastový přebal.

**Comment by Martin-Novacek-csCZ** [comment]
Na testovací server byla nasazena nová verze Relief, kde jsou opravené ty dvě věci.

**Comment by Neoralova** [comment]
Došlo k nedorozumění ohledně druhého bodu - Plastový přebal. V kolonce Ochranný obal jsme nechtěli odstranit hodnotu Plastový přebal, ale opravit chybné vložení - místo Plastový přebal tam bylo ochrannyobalplastovypřebal. To jsme chtěli opravit - přepsat na Plastový přebal. Omlouvám se za špatnou specifikaci a prosím o vložení hodnoty Plastový přebal.

**Comment by Martin-Novacek-csCZ** [comment]
Ok, předělám ještě dnes.

**Comment by Martin-Novacek-csCZ** [comment]
Na testovací server byla nasazena nová verze Relief, kde je opravena ta hodnota v Listu.
